import { GlossaryTerm } from "./types";

export const GLOSSARY: GlossaryTerm[] = [
  // Module 0: Fundamentals
  { term: "jq", definition: "A lightweight, high-performance command-line processor for JSON, typically used in CI/CD pipelines, AI workflows, and shell scripts." },
  { term: "Filter", definition: "The core concept in jq. Every expression is a filter that takes a JSON input and produces a JSON output (or stream)." },
  { term: "Identity Operator (.)", definition: "The simplest filter. Takes input and produces it unchanged. Commonly used for pretty-printing." },
  { term: "Pipe Operator (|)", definition: "Chains filters together, feeding the output of the left filter into the input of the right filter." },
  { term: "Immutability", definition: "jq treats values as immutable. Assignment works as though a full deep copy is performed." },
  
  // Module 1: Navigation
  { term: "Property Access (.key)", definition: "Extracts the value associated with a simple identifier-like key." },
  { term: "Complex Key Access ([\"key\"])", definition: "Required when keys contain special characters or spaces (e.g. .[\"key-name\"])." },
  { term: "Nested Access (.a.b)", definition: "Chaining filters to access deeply nested data. Equivalent to .a | .b." },
  { term: "Array Indexing (.[N])", definition: "Returns the element at the 0-based index N. Negative indices count backward." },
  { term: "Array Slicing (.[s:e])", definition: "Returns a subarray from start (inclusive) to end (exclusive)." },
  { term: "Optional Access (?)", definition: "Prevents errors if a path does not exist, outputting null instead." },

  // Module 2: Iteration & Core
  { term: "Iteration (.[] )", definition: "Generates a stream where each array element (or object value) is output separately." },
  { term: "Collection ([])", definition: "Collects all outputs generated by the filter inside into a single JSON array." },
  { term: "select(condition)", definition: "Passes input downstream only if the condition evaluates to true." },
  { term: "Recursive Descent (..)", definition: "Recursively descends the JSON structure, yielding every value contained within." },

  // Module 3: Transformation
  { term: "map(f)", definition: "Applies filter f to every element of the input array and collects results into a new array." },
  { term: "Object Construction ({k:v})", definition: "Creates a new JSON object. The value filter runs against current input." },
  { term: "to_entries / from_entries", definition: "Converts between an object and an array of {key, value} pairs." },
  { term: "group_by(.field)", definition: "Groups array elements with the same value for .field into subarrays." },
  { term: "sort_by(.field)", definition: "Sorts an array of objects based on the result of a filter applied to each element." },
  { term: "del(.path)", definition: "Removes the specified key and its value from an object." },
  { term: "add", definition: "Accumulates array elements: sums numbers, concatenates strings, or merges objects." },

  // Module 4: Advanced
  { term: "Variables ($name)", definition: "Stores the result of an expression into a variable for later use in the pipeline." },
  { term: "Update Assignment (|=)", definition: "Updates a field where the filter determines the new value based on the old value." },
  { term: "Alternative Operator (//)", definition: "Returns the left result unless it is false/null, otherwise returns the right default." },
  { term: "--stream", definition: "Parses large JSON files incrementally to reduce memory usage." }
];

export const SAMPLE_JSON = {
  "store": {
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  },
  "expensive": 10
};
