import { GlossaryTerm } from "./types";

export const GLOSSARY: GlossaryTerm[] = [
  // Module 0: Fundamentals
  { term: "jq", definition: "A lightweight, high-performance command-line processor for JSON, typically used in CI/CD pipelines, AI workflows, and shell scripts." },
  { term: "Filter", definition: "The core concept in jq. Every expression is a filter that takes a JSON input and produces a JSON output (or stream)." },
  { term: "Identity Operator (.)", definition: "The simplest filter. Takes input and produces it unchanged. Commonly used for pretty-printing." },
  { term: "Pipe Operator (|)", definition: "Chains filters together, feeding the output of the left filter into the input of the right filter." },
  { term: "Immutability", definition: "jq treats values as immutable. Assignment works as though a full deep copy is performed." },

  // Module 1: Navigation
  { term: "Property Access (.key)", definition: "Extracts the value associated with a simple identifier-like key." },
  { term: "Complex Key Access ([\"key\"])", definition: "Required when keys contain special characters or spaces (e.g. .[\"key-name\"])." },
  { term: "Nested Access (.a.b)", definition: "Chaining filters to access deeply nested data. Equivalent to .a | .b." },
  { term: "Array Indexing (.[N])", definition: "Returns the element at the 0-based index N. Negative indices count backward." },
  { term: "Array Slicing (.[s:e])", definition: "Returns a subarray from start (inclusive) to end (exclusive)." },
  { term: "Optional Access (?)", definition: "Prevents errors if a path does not exist, outputting null instead." },

  // Module 2: Iteration & Core
  { term: "Iteration (.[] )", definition: "Generates a stream where each array element (or object value) is output separately." },
  { term: "Collection ([])", definition: "Collects all outputs generated by the filter inside into a single JSON array." },
  { term: "select(condition)", definition: "Passes input downstream only if the condition evaluates to true." },
  { term: "Recursive Descent (..)", definition: "Recursively descends the JSON structure, yielding every value contained within." },

  // Module 3: Transformation
  { term: "map(f)", definition: "Applies filter f to every element of the input array and collects results into a new array." },
  { term: "Object Construction ({k:v})", definition: "Creates a new JSON object. The value filter runs against current input." },
  { term: "to_entries / from_entries", definition: "Converts between an object and an array of {key, value} pairs." },
  { term: "group_by(.field)", definition: "Groups array elements with the same value for .field into subarrays." },
  { term: "sort_by(.field)", definition: "Sorts an array of objects based on the result of a filter applied to each element." },
  { term: "del(.path)", definition: "Removes the specified key and its value from an object." },
  { term: "add", definition: "Accumulates array elements: sums numbers, concatenates strings, or merges objects." },

  // Module 4: Advanced
  { term: "Variables ($name)", definition: "Stores the result of an expression into a variable for later use in the pipeline." },
  { term: "Update Assignment (|=)", definition: "Updates a field where the filter determines the new value based on the old value." },
  { term: "Alternative Operator (//)", definition: "Returns the left result unless it is false/null, otherwise returns the right default." },
  { term: "--stream", definition: "Parses large JSON files incrementally to reduce memory usage." }
];

export const SAMPLE_JSON = {
  "store": {
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  },
  "expensive": 10
};

// --- 1. Docker Inspect Output (Infrastructure) ---
export const DOCKER_INSPECT_JSON = [
  {
    "Id": "a1b2c3d4e5",
    "Name": "/web-production",
    "State": {
      "Status": "running",
      "Running": true,
      "ExitCode": 0,
      "Health": { "Status": "healthy", "FailingStreak": 0 }
    },
    "Config": {
      "Image": "nginx:alpine",
      "Env": ["HOST=0.0.0.0", "PORT=80", "API_KEY=secret_123"],
      "Labels": { "com.docker.compose.service": "web", "org.opencontainers.image.version": "1.21" }
    },
    "NetworkSettings": {
      "Networks": {
        "app_net": { "IPAddress": "172.18.0.3", "Gateway": "172.18.0.1", "Aliases": ["web", "a1b2c3"] }
      }
    },
    "Mounts": [
      { "Type": "bind", "Source": "/host/nginx.conf", "Destination": "/etc/nginx/nginx.conf", "RW": true },
      { "Type": "volume", "Name": "logs_vol", "Source": "/var/lib/docker/volumes/logs/_data", "Destination": "/var/log/nginx", "RW": true }
    ]
  }
];

// --- 2. Looker Dashboard Element (BI/Analytics) ---
export const LOOKER_DASHBOARD_JSON = {
  "id": "123",
  "title": "Sales Overview",
  "dashboard_elements": [
    {
      "id": "456",
      "type": "vis",
      "title": "Monthly Revenue",
      "query": {
        "view": "orders",
        "fields": ["orders.created_month", "orders.total_amount"],
        "filters": { "orders.status": "complete" },
        "vis_config": {
          "type": "looker_line",
          "y_axis_gridlines": true,
          "series_labels": { "orders.total_amount": "Revenue" }
        }
      }
    },
    {
      "id": "789",
      "type": "vis",
      "title": "Top Customers",
      "query": {
        "view": "users",
        "fields": ["users.name", "orders.count"],
        "vis_config": { "type": "looker_grid", "show_view_names": false }
      }
    }
  ]
};

// --- 3. GenAI/OpenTelemetry Trace Log (AI Ops) ---
export const GENAI_TRACE_JSON = {
  "trace_id": "0af765",
  "spans": [
    {
      "name": "chat_completion",
      "kind": "CLIENT",
      "start_time_unix_nano": 1610000000000000,
      "end_time_unix_nano": 1610000002000000,
      "attributes": {
        "llm.system": "openai",
        "llm.request.model": "gpt-4",
        "llm.usage.prompt_tokens": 150,
        "llm.usage.completion_tokens": 40,
        "llm.usage.total_tokens": 190,
        "gen_ai.prompt.0.content": "Summarize this JSON data...",
        "gen_ai.completion.0.content": "Here is the summary..."
      },
      "status": { "code": "OK" }
    },
    {
      "name": "tool_execution",
      "kind": "INTERNAL",
      "attributes": { "tool.name": "calculator", "tool.args": "{\"x\": 5, \"y\": 10}" }
    }
  ]
};

// --- 4. SaaS Ingestion (Stripe-like Invoice) ---
export const STRIPE_INVOICE_JSON = {
  "object": "list",
  "data": [
    {
      "id": "in_123",
      "object": "invoice",
      "amount_due": 2500,
      "currency": "usd",
      "status": "paid",
      "lines": {
        "object": "list",
        "data": [
          { "id": "il_1", "amount": 2000, "description": "Pro Plan", "metadata": { "region": "eu" } },
          { "id": "il_2", "amount": 500, "description": "Seat Add-on", "metadata": { "region": "eu" } }
        ]
      }
    }
  ]
};

// --- 5. BigQuery Native JSON (Data Engineering) ---
export const BQ_JSON_EXPORT = [
  {
    "row_id": 1,
    "user_info": { "id": 99, "geo": { "city": "London", "coords": [51.5, -0.12] } },
    "custom_attributes": "[{\"key\":\"tier\", \"value\":\"gold\"}, {\"key\":\"source\", \"value\":\"web\"}]" // JSON string inside JSON
  },
  {
    "row_id": 2,
    "user_info": { "id": 100, "geo": { "city": "New York", "coords": [40.7, -74.0] } },
    "custom_attributes": "[{\"key\":\"tier\", \"value\":\"silver\"}]"
  }
];
